# fly.toml app configuration file for positive-vibes-backend
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# Ensure this app name matches the one on Fly.io (e.g., positive-vibes-project or positive-vibes-backend)
app = 'positive-vibes-project' # Adjusted based on recent deploy command
primary_region = 'iad'

# Use Paketo buildpacks to build the Node.js app
[build]
  builder = "paketobuildpacks/builder:full"

[http_service]
  # Match the port your Node.js app listens on (process.env.PORT || 3000)
  # Since logs show PORT=3000, set internal_port to 3000.
  internal_port = 3000 # Changed back to 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Keep on free tier setting
  processes = ['app']

# Keep the vm section if you specifically need 1GB memory.
# Otherwise, you can remove it for Fly's default free tier sizing (256MB).
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Optional: Health checks should also target the correct internal port
# [checks]
#   [checks.alive]
#     type = "tcp"
#     interval = "15s"
#     timeout = "2s"
#     grace_period = "5s"
#     port = 3000 # Check port 3000

